stop-words = "lemur-stopwords.txt"
prefix = "."

dataset = "drive/MyDrive/meta/data"
corpus = "file.toml"
index = "dataset-unigram-idx"

query-judgements = "./lista-unigram-qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[ranker]
method = "bm25"
k1 = 1.2
b = 0.75
k3 = 500
