stop-words = "drive/MyDrive/meta/lemur-stopwords.txt"
prefix = "."

dataset = "drive/MyDrive/meta/data"
corpus = "file.toml"
index = "dataset-trigram-idx"

query-judgements = "./lista-trigram-qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 3
filter = [{type = "icu-tokenizer", suppress-tags = true}, {type = "lowercase"}]

[ranker]
method = "bm25"
k1 = 1.2
b = 0.75
k3 = 500
